---
title: "Chess Masters Summary Report"
author: "Tom Hook"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: 
  html_document:
      toc: true
      toc_float: true
---

```{r, echo = FALSE}
# FILE:                   Masters Summary Report
# DESCRIPTION:            Creates a masters level table from the games data.

# AUTHOR:                 Tom Hook
# CONTACT:                thomashook1@outlook.com
# LAST UPDATED:           24/06/2023
# VERSION:                v0.1    
```

```{r, echo=FALSE, message=FALSE}
if(!require("pacman")) install.packages("pacman"); library (pacman)
pacman::p_load(readxl, dplyr, tidyverse, zoo, here, lubridate, rstudioapi, tidyr, 
               data.table, stringr, openxlsx, shiny, knitr)
```

```{r, echo = FALSE}
# Load relevant data
tblGames <- readRDS("Games.rds")
tblMasters <- readRDS("Masters.rds")
vecMasters <- tblMasters$Master
```

The highest rated player ever is `r tblGames$Master[which.max(tblGames$EloMaster)]`

Magnus hit his peak elo on `r tblMasters$MaxDate[tblMasters$Master == 'Carlsen, M']`

```{r, echo = FALSE, results = 'asis'}
for (master in vecMasters) {
  # Create section for each master (used in TOC)
  cat(paste0("# ", master, "\n\n"))
  
  # Filter the data for the current master
  tblMasterGames <- tblGames %>%
    filter(Master == master)
  
  # Master's highest ever elo, and when it   
  maxElo <- tblMasters$MaxElo[tblMasters$Master == master]
  if (!is.finite(maxElo)) {
    cat(paste0(master, " did not have a recorded rating.", "\n\n")) 
  } else {
    cat(paste0(master, " had a peak rating of ", maxElo, ".", "\n\n"))
    minDate <- tblMasters$MinDate[tblMasters$Master == master]
    cat(paste0("This rating was achieved in ", minDate, "\n\n"))
    
  # Plot elo over time
  p <- ggplot(tblMasterGames, aes(x = Date, y = EloMaster)) +
    geom_line() +
    labs(title = paste("Rating over Time for", master),
         x = "Year", y = "FIDE Rating")
  
  # Print the plot and ignore warnings
  suppressWarnings({
    print(p)
  })
  }
  # problem with the data... elos randomly dropping? gahhh
  
  # Add a blank line between the plot and table
  cat("\n\n")
  
  # Table of most common openings by Master for white pieces
  tblOpeningsWhite <- tblMasterGames %>%
    filter(PiecesMaster == "White") %>%
    group_by(Opening) %>%
    summarise(count = n()) %>%
    arrange(desc(count))
  
  # Extract the top 3 opening values
  tblTop3OpeningsWhite <- tblOpeningsWhite[1:3, ]
  
  # Print the top 3 openings with desired format ADD WHITE VS BLACK HERE
  cat("Most common openings with the white pieces:\n\n")
  for (i in 1:3) {
    cat(paste0(i, ". ", tblTop3OpeningsWhite$Opening[i], ". ", tblTop3OpeningsWhite$count[i], " times.", "\n"), 
        sep="\n")
  }
  
  # Add a blank line after the list
  cat("\n\n")
  
  # Table of most common openings by Master for white pieces
  tblOpeningsBlack <- tblMasterGames %>%
    filter(PiecesMaster == "Black") %>%
    group_by(Opening) %>%
    summarise(count = n()) %>%
    arrange(desc(count))
  
  # Extract the top 3 opening values
  tblTop3OpeningsBlack <- tblOpeningsBlack[1:3, ]
  
  # Print the top 3 openings with desired format ADD WHITE VS BLACK HERE
  cat("Most common openings with the black pieces:\n\n")
  for (i in 1:3) {
    cat(paste0(i, ". ", tblTop3OpeningsBlack$Opening[i], ". ", tblTop3OpeningsBlack$count[i], " times.", "\n"), 
        sep="\n")
  }
  
  # Add a blank line after the list
  cat("\n\n")
  
  
}
```

Consider loading moves into PGN reader with a link to https://chesstempo.com/pgn-viewer/                   
                   