---
title: "Profile: `r Master`"
author: "Tom Hook"
date: "`r format(Sys.Date(), '%d %B %y')`"
output: 
  flexdashboard::flex_dashboard:
    css: styles.css
    orientation: columns
    vertical_layout: fill
params:
  Master:
    label: "Select a Master"
    value: ""
---

```{r, echo = FALSE}
# FILE:                   Games Table
# DESCRIPTION:            Creates a table of all the masters games that the users can filter on.

# AUTHOR:                 Tom Hook
# CONTACT:                thomashook1@outlook.com
# LAST UPDATED:           09/07/2023
# VERSION:                v0.2    
```

```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
source("R Scripts/Snippets for Profiles/Setup.r")
```

Summary Page
=====

Column {data-width=300}
-----

```{r}
source("R Scripts/Snippets for Profiles/Profile Stats.r")
source("R Scripts/Snippets for Profiles/Games Per Year.r")
```

### <span style="font-size:x-large;">Profile</span>

Full Name: `r Master`

``` {r, echo = FALSE, results = 'asis'}
if (is.na(tblMasterProfile$FIDE_ID[1])) {
  cat("This player does not have a FIDE profile.")
} else {
  cat("Year of Birth: ", tblMasterProfile$B.day[1], "\n\n")
  cat("Peak Elo: ", intEloMax, "\n\n")
  cat(paste0("You can access their FIDE profile [here](https://ratings.fide.com/profile/", tblMasterProfile$FIDE_ID[1],           "){target=\"_blank\"}.", "\n\n"))
}
```

There are `r nrow(tblMasterGames)` games available in the dataset for `r Master`. `r format(dateGamesMax, "%Y")` was the year with most games recorded for, at `r max(tblGamesPerYear$Count)`.  

Column {data-width=400}
-----

### <span style="font-size:x-large;">FIDE Rating over Time</span>

```{r}
source("R Scripts/Snippets for Profiles/Elo Timeseries.r")

plotEloTimeseries
```

### <span style="font-size:x-large;">Games Per Year in the Database</span>

```{r}
plotGamesPerYear
```

Column {.tabset .tabset-fade data-width=300}
-----

```{r}
source("R Scripts/Snippets for Profiles/Common Openings.r")
source("R Scripts/Snippets for Profiles/Result Distribution.r")
```

<span style="font-size:x-large;">Stats by White/Black Pieces</span>

### <span style="font-size:large;">Combined</span>

##### Result Distribution:

```{r  fig.width=5, fig.height=4}
plotResults
```

##### Most common openings played:

```{r}
tblOpenings
```

### <span style="font-size:large;">White</span>

##### Result Distribution:

```{r  fig.width=5, fig.height=4}
plotResultsWhite
```

##### Most common openings played:

```{r}
tblOpeningsWhite
```

### <span style="font-size:large;">Black</span>

##### Result Distribution:

```{r  fig.width=5, fig.height=4}
plotResultsBlack
```

##### Most common openings played:

```{r}
tblOpeningsBlack
```

List of Games
=====

```{r, echo = FALSE, warning = FALSE}
source("R Scripts/Snippets for Profiles/Table of Master Games.r")

dtMasterGames
```
